import React from 'react';

const Home = () => {
    return (
        <div className='lg:px-12 font-semibold my-5'>
            <h1>Finding the best book blogs to follow is becoming more and more popular and while books will always be my go-to, when it comes to my reading material of choice, I also love spending a lazy Saturday morning in bed with the sun streaming through my window catching up on the latest posts from some of my favourite book bloggers.

            And while back in the infancy of book blogging, when most blogs about books for book lovers were unsophisticated at best, and downright dreary at worst, these days the best book bloggers are the proud owners of some seriously sophisticated sites. From the crème de la crème of bookish photography, to book memes, sleek lay outs and more, these bloggers are proving that books are anything but boring.  There are a number of fellow book bloggers I’ve been following for a while, but most of my current favourites have been sites I’ve come across in the weeks that have passed since my book blog won the London Book Fair’s Book Blogger of the Year award, meaning there are ample posts for me to read, requiring endless hours in bed as I pour over the best book review blogs.

            From the new kid on the book blogging block, to some long-time and firm favourites, I’ve rounded up thirteen of the most stylish book lover blogs to follow. Perfect for anyone wanting to up their reading repertoire or in need of some beautifully bookish inspiration. And so, whether you’re looking for book recommendation blogs or book reviews blogs, book bloggers to follow, the very best new books to read, the latest mystery books, or some inspiration for your next book club, read on for my very favourite and most popular book blogs.
            Finding the best book blogs to follow is becoming more and more popular and while books will always be my go-to, when it comes to my reading material of choice, I also love spending a lazy Saturday morning in bed with the sun streaming through my window catching up on the latest posts from some of my favourite book bloggers.

            And while back in the infancy of book blogging, when most blogs about books for book lovers were unsophisticated at best, and downright dreary at worst, these days the best book bloggers are the proud owners of some seriously sophisticated sites. From the crème de la crème of bookish photography, to book memes, sleek lay outs and more, these bloggers are proving that books are anything but boring.  There are a number of fellow book bloggers I’ve been following for a while, but most of my current favourites have been sites I’ve come across in the weeks that have passed since my book blog won the London Book Fair’s Book Blogger of the Year award, meaning there are ample posts for me to read, requiring endless hours in bed as I pour over the best book review blogs.
            And while back in the infancy of book blogging, when most blogs about books for book lovers were unsophisticated at best, and downright dreary at worst, these days the best book bloggers are the proud owners of some seriously sophisticated sites. From the crème de la crème of bookish photography, to book memes, sleek lay outs and more, these bloggers are proving that books are anything but boring.  There are a number of fellow book bloggers I’ve been following for a while, but most of my current favourites have been sites I’ve come across in the weeks that have passed since my book blog won the London Book Fair’s Book Blogger of the Year award, meaning there are ample posts for me to read, requiring endless hours in bed as I pour over the best book review blogs.
            And while back in the infancy of book blogging, when most blogs about books for book lovers were unsophisticated at best, and downright dreary at worst, these days the best book bloggers are the proud owners of some seriously sophisticated sites. From the crème de la crème of bookish photography, to book memes, sleek lay outs and more, these bloggers are proving that books are anything but boring.  There are a number of fellow book bloggers I’ve been following for a while, but most of my current favourites have been sites I’ve come across in the weeks that have passed since my book blog won the London Book Fair’s Book Blogger of the Year award, meaning there are ample posts for me to read, requiring endless hours in bed as I pour over the best book review blogs.
            And while back in the infancy of book blogging, when most blogs about books for book lovers were unsophisticated at best, and downright dreary at worst, these days the best book bloggers are the proud owners of some seriously sophisticated sites. From the crème de la crème of bookish photography, to book memes, sleek lay outs and more, these bloggers are proving that books are anything but boring.  There are a number of fellow book bloggers I’ve been following for a while, but most of my current favourites have been sites I’ve come across in the weeks that have passed since my book blog won the London Book Fair’s Book Blogger of the Year award, meaning there are ample posts for me to read, requiring endless hours in bed as I pour over the best book review blogs.

            From the new kid on the book blogging block, to some long-time and firm favourites, I’ve rounded up thirteen of the most stylish book lover blogs to follow. Perfect for anyone wanting to up their reading repertoire or in need of some beautifully bookish inspiration. And so, whether you’re looking for book recommendation blogs or book reviews blogs, book bloggers to follow, the very best new books to read, the latest mystery books, or some inspiration for your next book club, read on for my very favourite and most popular book blogs.</h1>
        </div>
    );
};

export default Home;